### ISSUE TITLE
Mobile menu review

### ISSUE THREAD

**Issue by aeh1707** [godiarksel/port-folio#9]
Feel free to leave any comments or review about the mobile menu.

**Comment by aeh1707** [comment]
Your work was great overall, I have a few points you can improve.

- You're having an issue with horizontal scroliing.

**Comment by Felix45** [comment]
- Please consider blurring the background of the overlay so that the white text on the menu can be read clearly by users

**Comment by godiarksel** [comment]
Fixed issue with horizontal scrolling and blurred overlay background.
